#include <bits/stdc++.h>
using namespace std;

template<typename T>
class FenwickTree {
    vector<T> tree;
public:
    FenwickTree(int n) : tree(n + 1) {}
    void update(int i, T val) {
        for (; i < tree.size(); i += i & -i) {
            tree[i] += val;
        }
    }
    T pre(int i) const {
        T res = 0;
        for (; i > 0; i &= i - 1) {
            res += tree[i];
        }
        return res;
    }
    T query(int l, int r) const {
        if (r < l) return 0;
        return pre(r) - pre(l - 1);
    }
};

// generated by deepseek
// int main() {
//     ios::sync_with_stdio(false);
//     cin.tie(nullptr);
//     cin.exceptions(ios::badbit | ios::failbit);

//     int n;
//     cin >> n;
//     vector<int> pos(n + 1);
//     for (int i = 1; i <= n; i++) {
//         int x;
//         cin >> x;
//         pos[x] = i;
//     }

//     FenwickTree<long long> bitCnt(n), bitSum(n);
//     vector<long long> f(n + 1);
//     long long invCnt = 0;

//     for (int k = 1; k <= n; k++) {
//         int p = pos[k];
        
//         // 1. 新增逆序对：已选位置中比 p 大的个数
//         invCnt += bitCnt.query(p + 1, n);
        
//         // 2. 插入当前位置
//         bitCnt.update(p, 1);
//         bitSum.update(p, p);
        
//         // 3. 计算聚拢代价
//         int target = (k + 1) / 2;
//         int lo = 1, hi = n;
//         while (lo < hi) {
//             int mid = (lo + hi) / 2;
//             if (bitCnt.pre(mid) >= target) hi = mid;
//             else lo = mid + 1;
//         }
//         int median = lo;
        
//         long long cntL = bitCnt.query(1, median - 1);
//         long long sumL = bitSum.query(1, median - 1);
//         long long cntR = bitCnt.query(median + 1, n);
//         long long sumR = bitSum.query(median + 1, n);
        
//         // 修正公式：目标位置是从 median - cntL 开始的连续区间
//         long long leftCost = cntL * median - cntL * (cntL + 1) / 2 - sumL;
//         long long rightCost = sumR - cntR * median - cntR * (cntR + 1) / 2;
//         long long gatherCost = leftCost + rightCost;
        
//         f[k] = invCnt + gatherCost;
//     }

//     for (int k = 1; k <= n; k++) {
//         cout << f[k] << " \n"[k == n];
//     }
//     return 0;
// }

// 复习
int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    cin.exceptions(ios::badbit | ios::failbit);

    int n;
    cin >> n;
    vector<int> pos(n+1); vector<long long> f(n+1);
    for (int i=1; i<=n; i++) {
        int x; cin >> x; pos[x] = i;
    }
    
    FenwickTree<long long> invCnt(n), posSum(n);
    long long preInv = 0;

    for (int k=1; k<=n; k++) {
        auto p = pos[k];
        preInv += invCnt.query(p+1, n);

        invCnt.update(p, 1); posSum.update(p, p);
        auto llen = (k + 1) / 2, rlen = k / 2;
        int lo = 1, hi = n;
        while (lo <= hi) {
            auto mid = (lo + hi) / 2;
            if (invCnt.pre(mid) >= llen) hi = mid-1;
            else lo = mid + 1;
        }
        long long x = hi + 1;

        auto lcost = (x + x + 1 - llen) * llen / 2 - posSum.pre(x);
        auto rcost = posSum.query(x+1, n) - (x + 1 + x + rlen) * rlen / 2;

        f[k] = preInv + lcost + rcost;
    }
    
    for (int k=1; k<=n; k++) {
        cout << f[k] << " \n"[k==n];
    }

    return 0;
}