# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scheduler_pb2 as scheduler__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub(object):
    """Scheduler 服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/miniray.SchedulerService/RegisterWorker',
                request_serializer=scheduler__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=scheduler__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/miniray.SchedulerService/Heartbeat',
                request_serializer=scheduler__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=scheduler__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.PullTask = channel.unary_unary(
                '/miniray.SchedulerService/PullTask',
                request_serializer=scheduler__pb2.PullTaskRequest.SerializeToString,
                response_deserializer=scheduler__pb2.PullTaskResponse.FromString,
                _registered_method=True)
        self.ReportTaskResult = channel.unary_unary(
                '/miniray.SchedulerService/ReportTaskResult',
                request_serializer=scheduler__pb2.ReportTaskResultRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ReportTaskResultResponse.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/miniray.SchedulerService/SubmitTask',
                request_serializer=scheduler__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=scheduler__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.GetTaskResult = channel.unary_unary(
                '/miniray.SchedulerService/GetTaskResult',
                request_serializer=scheduler__pb2.GetTaskResultRequest.SerializeToString,
                response_deserializer=scheduler__pb2.GetTaskResultResponse.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """Scheduler 服务
    """

    def RegisterWorker(self, request, context):
        """Worker 注册
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Worker 心跳
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullTask(self, request, context):
        """Worker 拉取任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTaskResult(self, request, context):
        """Worker 上报任务结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """客户端提交任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskResult(self, request, context):
        """客户端获取任务结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=scheduler__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=scheduler__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=scheduler__pb2.HeartbeatRequest.FromString,
                    response_serializer=scheduler__pb2.HeartbeatResponse.SerializeToString,
            ),
            'PullTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PullTask,
                    request_deserializer=scheduler__pb2.PullTaskRequest.FromString,
                    response_serializer=scheduler__pb2.PullTaskResponse.SerializeToString,
            ),
            'ReportTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTaskResult,
                    request_deserializer=scheduler__pb2.ReportTaskResultRequest.FromString,
                    response_serializer=scheduler__pb2.ReportTaskResultResponse.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=scheduler__pb2.SubmitTaskRequest.FromString,
                    response_serializer=scheduler__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'GetTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskResult,
                    request_deserializer=scheduler__pb2.GetTaskResultRequest.FromString,
                    response_serializer=scheduler__pb2.GetTaskResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'miniray.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('miniray.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """Scheduler 服务
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/miniray.SchedulerService/RegisterWorker',
            scheduler__pb2.RegisterWorkerRequest.SerializeToString,
            scheduler__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/miniray.SchedulerService/Heartbeat',
            scheduler__pb2.HeartbeatRequest.SerializeToString,
            scheduler__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/miniray.SchedulerService/PullTask',
            scheduler__pb2.PullTaskRequest.SerializeToString,
            scheduler__pb2.PullTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/miniray.SchedulerService/ReportTaskResult',
            scheduler__pb2.ReportTaskResultRequest.SerializeToString,
            scheduler__pb2.ReportTaskResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/miniray.SchedulerService/SubmitTask',
            scheduler__pb2.SubmitTaskRequest.SerializeToString,
            scheduler__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/miniray.SchedulerService/GetTaskResult',
            scheduler__pb2.GetTaskResultRequest.SerializeToString,
            scheduler__pb2.GetTaskResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
